---
nombre_nota: "hadling exception"
alias: hadling exception
letras: "pytt"
referencias: "[[TODO/🏛️python tutorial (dcb4c).md]]"
tipo_nota: "📑"
hash: "8a6d65"
parent_hash: "aea5a"
---

#nota/📑

# 📑hadling exception
<div class="hash">(8a6d65)</div>

> [!NOTE] 
capture [[📑exception (pytt)|exception]] with __except__ [[📑exception classes (pytt)|exception class]]
```python
while True:

    try:

        x = int(input("Please enter a number: "))

        break

    except ValueError:

        print("Oops!  That was no valid number.  Try again...")
```

[[📑capture multiple exceptions (pytt)|capture multiple exceptions]]
[[📑arguments of the exception (pytt)|arguments of the exception]]
[[📑handling unknown exception (pytt)|handling unknown exception]]





- [ ] recordar  [start:: 2024-10-17]
